### PR TITLE
Add Dockerfile for simple dochunt-check image

### PR DESCRIPTION
**Pull request by m-messiah**
Useful for docker-based CI (for example Gitlab CI)

### CODE REVIEW

**Comment by m-messiah** [comment]
For example, in Gitlab CI, you can use:
doc-hunt:
  image: mmessiah/doc-hunt
  stage: check
  script:
    - doc-hunt check -e

And fail build, if documentation unchanged

**Comment by m-messiah** [comment]
Hm, build failed, but it is not my fail. So strange.

**Comment by antham** [comment]
Pretty weird indeed, maybe a linter was updated, anyway it's fixed, you can rebase master branch.

**Comment by m-messiah** [comment]
Same result =(

**Comment by antham** [comment]
That's fine a rebuild solve this issue, it's a random issue occuring from time to time, something link to how tests are ran, I have to fixed it...

**Comment by antham** [comment]
Now it's available on dockerhub : https://github.com/antham/doc-hunt#install

**Pull request merged**
